# ä¸æ˜¾ç¤ºæ¢è¡Œç¬¦
add_newline = false

# è‡ªå®šä¹‰æç¤ºç¬¦ç¬¦å·
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

# è‡ªå®šä¹‰ç›®å½•æ˜¾ç¤º
[directory]
truncation_length = 3
truncation_symbol = "â€¦/"

# è‡ªå®šä¹‰ Git çŠ¶æ€æ˜¾ç¤º
[git_branch]
symbol = "ğŸŒ± "
truncation_length = 8
truncation_symbol = ""
